name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    env:
      ONLINE_STORE: ${{ secrets.ONLINE_STORE }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Uso Node 20 para compilar Angular sin Oryx
      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

      # Deploy SIN volver a buildar (evita Oryx/Node 18)
      - name: Upload prebuilt app to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        id: swa
        with:
          azure_static_web_apps_api_token: ${{ env.ONLINE_STORE }}
          action: "upload"
          app_location: "dist/online-store/browser"
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"


